### ISSUE TITLE
Error at pyinstaller

### ISSUE THREAD

**Issue by chiften1371** [rdbende/Sun-Valley-ttk-theme#38]
Hello. This error is displayed during the execution of the program when we get an Exe with the pyinstaller. Thank you for your guidance

`Traceback (most recent call last):
  File "main2.py", line 7, in <module>
  File "sv_ttk\__init__.py", line 59, in <lambda>
  File "sv_ttk\__init__.py", line 18, in wrapper
_tkinter.TclError: couldn't read file "C:\Users\rahbar\AppData\Local\Temp\_MEI471922\sv_ttk\sun-valley.tcl": no such file or directory`

**Comment by rdbende** [comment]
Hi!
You should add `--collect-data sv_ttk` to the Pyinstaller command. It wiil collect all necessary files from the module.

**Comment by rohankishore** [comment]
Getting the error "ModuleNotFoundError: No module named 'sv_ttk'" when trying to open the exe file... btw, this's my pyinstaller command: pyinstaller --onefile -w .\scratch_3.py --hidden-import wikipedia --collect-data sv_ttk

**Comment by lmjaedentai** [comment]
<img width="316" alt="image" src="https://github.com/rdbende/Sun-Valley-ttk-theme/assets/63090071/738a4a97-b289-4a68-9200-8053c3fa08db">
why does this error occur?
